SHELL := bash
NAME := storage-publiclink

include ../../.bingo/Variables.mk
include ../../.make/default.mk
include ../../.make/deprecate.mk
include ../../.make/recursion.mk
include ../../.make/go.mk
include ../../.make/release.mk
include ../../.make/docs.mk
