SHELL := bash
NAME := idp

include ../../.bingo/Variables.mk
include ../../.make/default.mk
include ../../.make/deprecate.mk
include ../../.make/recursion.mk
include ../../.make/go.mk
include ../../.make/release.mk
include ../../.make/docs.mk

.PHONY: node-generate-prod
node-generate-prod: assets

.PHONY: assets
assets: pnpm-build \
		assets/identifier/static \
		assets/identifier/static/favicon.ico \
		assets/identifier/static/icon-lilac.svg

assets/identifier/static:
	mkdir -p assets/identifier/static

.PHONY: assets/identifier/static/favicon.ico # force overwrite
assets/identifier/static/favicon.ico:
	cp src/images/favicon.ico assets/identifier/static/favicon.ico

.PHONY: assets/identifier/static/icon-lilac.svg
assets/identifier/static/icon-lilac.svg:
	cp src/images/icon-lilac.svg assets/identifier/static/icon-lilac.svg

.PHONY: pnpm-build
pnpm-build: node_modules
	#pnpm lint #TODO: activate
	#pnpm test #TODO: activate
	pnpm build

.PHONY: node_modules
node_modules:
	pnpm install

.PHONY: ci-node-check-licenses
ci-node-check-licenses: node_modules
	pnpm licenses:check

.PHONY: ci-node-save-licenses
ci-node-save-licenses: node_modules
	pnpm licenses:csv
	pnpm licenses:save
