SHELL := bash
NAME := idm
TAGS := disable_crypt

include ../../.bingo/Variables.mk
include ../../.make/default.mk
include ../../.make/recursion.mk
include ../../.make/go.mk
include ../../.make/release.mk
include ../../.make/docs.mk
