# maintain v2 separate mocks dir
dir: "{{.InterfaceDir}}/mocks"
structname: "{{.InterfaceName}}"
filename: "{{.InterfaceName | snakecase }}.go"
pkgname: mocks

template: testify
packages:
  github.com/opencloud-eu/opencloud/services/search/pkg/engine:
    interfaces:
      Engine: {}
  github.com/opencloud-eu/opencloud/services/search/pkg/content:
    interfaces:
      Extractor: {}
      Retriever: {}
  github.com/opencloud-eu/opencloud/services/search/pkg/search:
    interfaces:
      Searcher: {}